# Generated by Django 4.2.6 on 2023-11-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="order_cart",
            field=models.ManyToManyField(to="store.car"),
        ),
    ]
