# Generated by Django 4.2.7 on 2023-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_client_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartype",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
