# Generated by Django 4.2.7 on 2023-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_cartype_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="images")),
            ],
        ),
        migrations.AlterField(
            model_name="cartype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_image"),
        ),
    ]
