# Generated by Django 4.2.7 on 2023-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_image/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="car-images/"),
        ),
    ]
