# Generated by Django 4.2.7 on 2023-12-15 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_cartype_image_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartype",
            name="image",
        ),
    ]
