# Generated by Django 4.2.7 on 2023-12-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_remove_cartype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_image/"),
        ),
    ]
