# Generated by Django 4.2.7 on 2024-01-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=999, null=True),
        ),
    ]
