# Generated by Django 4.2.7 on 2024-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_url",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
